### ISSUE TITLE
Minikube Preferences value is not respected

### ISSUE THREAD

**Issue by odockal** [podman-desktop/extension-minikube#215]
I was playing around with minikube, I have set Preferences minikube property (minikube binary path) to a non-existing binary and tried to create a cluster (expecting it would fail), but it did not. So I assume that the property was not respected.

![Image](https://github.com/user-attachments/assets/fc011e88-42a8-475b-b657-6f4c675b5318)

There is also no button to open file manager. Although I appreciate the possibility to type the path into an input. There is also no validation present which would be great.

**Comment by axel7083** [comment]
Hummm, this might have been addressed by https://github.com/podman-desktop/extension-minikube/pull/224 (not included in 0.4.0)

**Comment by tony-sol** [comment]
So sad it's not working now :c

**Comment by axel7083** [comment]
> i believe, something wrong with

Could you retry with the nightly version of the minikube extension `ghcr.io/podman-desktop/podman-desktop-extension-minikube:nightly` ? This latest version contain the fix https://github.com/podman-desktop/extension-minikube/pull/224

See https://podman-desktop.io/docs/extensions/install for installing custom extension

**Comment by tony-sol** [comment]
@axel7083 

nightly version of extension not working with v1.14.1 of podman desktop

```
Error: require() of ES Module /Users/tony/.local/share/containers/podman-desktop/plugins/ghcriopodmandesktoppodmandesktopextensionminikube/dist/extension.js from /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs not supported. extension.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead either rename extension.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/tony/.local/share/containers/podman-desktop/plugins/ghcriopodmandesktoppodmandesktopextensionminikube/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
Stack trace:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/tony/.local/share/containers/podman-desktop/plugins/ghcriopodmandesktoppodmandesktopextensionminikube/dist/extension.js from /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs not supported.
extension.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename extension.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/tony/.local/share/containers/podman-desktop/plugins/ghcriopodmandesktoppodmandesktopextensionminikube/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at c._load (node:electron/js2c/node_init:2:16955)
    at _module._load (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:151:38636)
    at Xde.doRequire (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:151:65620)
    at Xde.loadRuntime (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:151:66331)
    at Xde.loadExtension (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:151:55697)
```

**Comment by axel7083** [comment]
Thanks @tony-sol you were right, we had a problem with the latest build of minikube, this has just been fixed by https://github.com/podman-desktop/extension-minikube/pull/238

Could you retry with `ghcr.io/podman-desktop/podman-desktop-extension-minikube:253bb4ccf231547357c6ba432925eabf8fa2474b` ?

**Comment by tony-sol** [comment]
@axel7083 sure, it installed well, see no error, but the main issue is still there - it created `~/.minikube` while calling minikube binary like without MINIKUBE_HOME

Also, my `${XDG_DATA_HOME:~/.local/share}/containers/podman-desktop/configuration/settings.json`:

```json
{
  "welcome.version": "initial",
  "telemetry.check": true,
  "telemetry.enabled": false,
  "kubernetes.Kubeconfig": "/Users/tony/.local/share/kube/config",
  "extensions.disabled": [],
  "kubectl.binary.installKubectlSystemWide": true,
  "lima.type": "docker",
  "compose.binary.installComposeSystemWide": true,
  "terminal.integrated.fontSize": 13,
  "editor.integrated.fontSize": 14,
  "lima.socket": "/Users/tony/.local/share/lima/default/sock/docker.sock",
  "extensions.ignoreRecommendations": true,
  "preferences.login.minimize": true,
  "docker.context": "limactl",
  "window.bounds": {
    "x": 366,
    "y": 137,
    "width": 1084,
    "height": 827
  },
  "podman.system.connections.remote": true,
  "releaseNotesBanner.show": "1.14.1",
  "dockerCompatibility.enabled": true,
  "tasks.StatusBar": true,
  "minikube.home": "/Users/tony/.local/share/minikube/",
  "layers-explorer.cacheSize": 100,
  "lima.name": "default",
  "tasks.Toast": true
}
```

**Comment by axel7083** [comment]
> [@axel7083](https://github.com/axel7083) sure, it installed well, see no error, but the main issue is still there - it created `~/.minikube` while calling minikube binary like without MINIKUBE_HOME

@tony-sol I am not sure exactly to understand the problem 🤔 . From my understanding you would like to be able to use minikube executable from the terminal with `MINIKUBE_HOME` value set as the preference in podman desktop ? This is not a feature provided by podman desktop :/

Podman Desktop is using the value provided in the preference when starting a cluster deleting etc.

![Image](https://github.com/user-attachments/assets/a8699c70-efe1-44a3-919f-d70331b2badb)

> In the background, Podman Desktop run the same command you would in the terminal, but provide the MINIKUBE_HOME if the user provided a value in the preference.

**Comment by axel7083** [comment]
> Now, looks like it either not read from settings.json via extensionApi.configuration.getConfiguration() or not applied in binary calls via extensionApi.process.exec()

@tony-sol could you provide a reproducer of the problem you are encountering ? I am doing the following steps, and I am able to use the custom home directory :/

1. install minikube extension `ghcr.io/podman-desktop/podman-desktop-extension-minikube:253bb4ccf231547357c6ba432925eabf8fa2474b`
2. assert version (0.5.0-next)
![Image](https://github.com/user-attachments/assets/0b22f308-3346-4620-88f9-21668e6b2daf)

3. change the minikube home directory preference
![Image](https://github.com/user-attachments/assets/0311ba38-5647-44dd-9853-2b01d52be251)

4. assert custom directory empty

```
$: ls /home/axel7083/.local/share/minikube
<nothing>
```

5. Create a minikube cluster from podman desktop

![Image](https://github.com/user-attachments/assets/9a04534d-28eb-4625-bd54-1904ba42ac98)

6. assert `minikube` container running

![Image](https://github.com/user-attachments/assets/cdafaaf7-0aa3-4b7f-938f-130c42c2f076)

7. assert minikube cluster listed in Resource page

![Image](https://github.com/user-attachments/assets/34507afc-ce54-415b-aea5-ec6036445263)

8. stop the cluster from the Resource page

![Image](https://github.com/user-attachments/assets/d594f4de-fba2-45e2-b1e3-21bd1cfae7ce)

9. assert cluster is stopped

10. check status from CLI
```
$: export MINIKUBE_HOME=/home/axel7083/.local/share/minikube && export MINIKUBE_ROOTLESS=true && minikube status
minikube
type: Control Plane
host: Stopped
kubelet: Stopped
apiserver: Stopped
kubeconfig: Stopped
```

**Comment by tony-sol** [comment]
@axel7083 here is a few steps to see the problem:
- configure podman desktop minikube extension to use any directory except in home
- completely quit from podman desktop (like, kill process)
- remove or rename your `~/.minikube` directory
- launch podman desktop
- see a new ~/.minikube directory

Also: extension doesn't see already existed - see, there are no play/stop buttons until i start minikube manually from cli

![Image](https://github.com/user-attachments/assets/1af43eae-3a07-4db9-8480-4be91762a568)

Also: starting minikube via interface, not passing KUBECONFIG env (which is  "kubernetes.Kubeconfig" in settings.json)

**Comment by tony-sol** [comment]
For me, the whole point of `"minikube.home"` and `"kubernetes.Kubeconfig"` in settings.json is to keep my home directory as clean as possible by letting me to configure minikube and kubectl environment, which is not accessible outside of shell (those `MINIKUBE_HOME`, `KUBECONFIG`, etc.)

And it's really important to keep consistency between every tool around minikube and kubectl; if one tool uses e.g. `MINIKUBE_HOME` while other don't - everything become messed up

**Comment by axel7083** [comment]
Okey I figure it out, the problem is not the same as the one explained in this issue. I opened https://github.com/podman-desktop/extension-minikube/issues/242.

**Comment by tony-sol** [comment]
@axel7083 sorry, another question - there also should be `KUBECONFIG` added into `getMinikubeAdditionalEnvs` with value from settings, like

```
export function getKubeConfig(): string | undefined {
  const kubernetesConfiguration = extensionApi.configuration.getConfiguration('kubernetes');
  const kubeConfig = minikubeConfiguration.get<string>('Kubeconfig');
  // Check env if configuration is not applied in UI
  if (!kubeConfig) {
    const env = process.env;
    return env.KUBECONFIG;
  } else {
    return kubeConfig;
  }
}

export function getMinikubeAdditionalEnvs(): Record<string, string> {
  const env: Record<string, string> = {
    PATH: getMinikubePath(),
  };
  const minikubeHome = getMinikubeHome();
  if (minikubeHome) {
    env['MINIKUBE_HOME'] = minikubeHome;
  }
  const kubeConfig = getKubeConfig();
  if (kubeConfig) {
    env['KUBECONFIG'] = kubeConfig;
  }
  return env;
}
```

To prevent problem with `E1120 17:53:32.745267   45820 status.go:417] kubeconfig endpoint: get endpoint: "minikube" does not appear in $KUBECONFIG`

**Comment by axel7083** [comment]
@tony-sol it makes sense 👍 , since you find the potential solution, you should open a PR !

**Comment by axel7083** [comment]
Closing this issue as completed by
- https://github.com/podman-desktop/extension-minikube/pull/245
- https://github.com/podman-desktop/extension-minikube/pull/243
- https://github.com/podman-desktop/extension-minikube/pull/224
